main: fr.peaceandcube.pacfirstplayed.PACFirstPlayed
name: PACFirstPlayed
description: A plugin showing the date you joined the server
version: 1.2.1
author: YanisBft
website: https://github.com/PeaceAndCubeMC/PACFirstPlayed
api-version: 1.13

depend: [pAcPI]

commands:
  firstplayed:
    description: Shows when you joined the server
    aliases: fp
    permission: firstplayed.me
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/firstplayed [<player>]"
  fpdate:
    description: Shows who joined the server on a date
    permission: firstplayed.date
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/fpdate <date>"

permissions:
  firstplayed.me:
    description: Allows you to get your own join date
    default: op
  firstplayed.other:
    description: Allows you to get another player join date
    default: op
  firstplayed.date:
    description: Allows to see who joined the server on a date
    default: op
