name: PACFirstPlayed
version: 1.1.0
author: Yanis48
main: fr.peaceandcube.pacfirstplayed.PACFirstPlayed
api-version: 1.13

commands:
  firstplayed:
    description: Shows when you joined the server
    aliases: fp
    permission: firstplayed.me
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/firstplayed [<player>]"
  fpdate:
    description: Shows who joined the server on a date
    permission: firstplayed.date
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/fpdate <date>"

permissions:
  firstplayed.me:
    description: Allows you to get your own join date
    default: op
  firstplayed.other:
    description: Allows you to get another player join date
    default: op
  firstplayed.date:
    description: Allows to see who joined the server on a date
    default: op
